# 06  Regression Model Demo 3 - Logistic Regression

In [1]:
import pandas as pd
import statsmodels.formula.api as sm

In [9]:
df = pd.read_csv('feedback_mtcars.csv')
df

                   Cars   mpg  cyl   disp   hp  drat  Feedback
0              MazdaRX4  21.0    6  160.0  110  3.90         1
1          MazdaRX4_WAG  21.0    6  160.0  110  3.90         0
2            Datsun_710  22.8    4  108.0   93  3.85         1
3        Hornet_4_Drive  21.4    6  258.0  110  3.08         1
4     Hornet_Sportabout  18.7    8  360.0  175  3.15         1
5               Valiant  18.1    6  225.0  105  2.76         1
6            Duster_360  14.3    8  360.0  245  3.21         0
7             Merc_240D  24.4    4  146.7   62  3.69         0
8              Merc_230  22.8    4  140.8   95  3.92         1
9              Merc_280  19.2    6  167.6  123  3.92         0
10            Merc_280C  17.8    6  167.6  123  3.92         0
11           Merc_450SE  16.4    8  275.8  180  3.07         0
12           Merc_450SL  17.3    8  275.8  180  3.07         1
13          Merc_450SLC  15.2    8  275.8  180  3.07         1
14   Cadillac_Fleetwood  10.4    8  472.0  205  2.93         1
15  Lincoln_Continental  10.4    8  460.0  215  3.00         0
16    Chrysler_Imperial  14.7    8  440.0  230  3.23         1
17             Fiat_128  32.4    4   78.7   66  4.08         1
18          Honda_Civic  30.4    4   75.7   52  4.93         0
19       Toyota_Corolla  33.9    4   71.1   65  4.22         0
20        Toyota_Corona  21.5    4  120.1   97  3.70         0

In [13]:
y = df['Feedback']
x = df[['mpg','hp','cyl']]
x

     mpg   hp  cyl
0   21.0  110    6
1   21.0  110    6
2   22.8   93    4
3   21.4  110    6
4   18.7  175    8
5   18.1  105    6
6   14.3  245    8
7   24.4   62    4
8   22.8   95    4
9   19.2  123    6
10  17.8  123    6
11  16.4  180    8
12  17.3  180    8
13  15.2  180    8
14  10.4  205    8
15  10.4  215    8
16  14.7  230    8
17  32.4   66    4
18  30.4   52    4
19  33.9   65    4
20  21.5   97    4

In [14]:
y = df['Feedback']
x = df[['mpg','hp', 'cy']]
y

KeyError: "['cy'] not in index"

In [11]:
model = sm.Logit(y, x)
result = model.fit()

Optimization terminated successfully.
         Current function value: 0.675937
         Iterations 4

In [12]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:               Feedback   No. Observations:                   21
Model:                          Logit   Df Residuals:                       18
Method:                           MLE   Df Model:                            2
Date:                Thu, 10 Jan 2019   Pseudo R-squ.:                 0.02323
Time:                        21:24:20   Log-Likelihood:                -14.195
converged:                       True   LL-Null:                       -14.532
                                        LLR p-value:                    0.7135
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
mpg           -0.0400      0.055     -0.734      0.463      -0.147       0.067
hp            -0.0101      0.022     -0.461      0.645      -0.053       0.033
cyl            0.3723      0.615      0.605      0.545      -0.834       1.578
==============================================================================
"""

# End of Regression Model Demo 3